name: merge automated ISBN updates into main
on:
  push:
    branches: ['update-isbn-ranges/JENKINS-**']
permissions:
  contents: write
jobs:
  Test_And_Merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Apply current changes
        run: |
          git config --global user.email "jenkins@creativecouple.de"
          git config --global user.name "Jenkins"
          git rebase $GITHUB_SHA

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test and format the changes
        run: mvn --batch-mode clean verify -Dgpg.skip=true

      - name: Merge changes
        run: |
          git commit -a --amend --no-edit --allow-empty
          git rebase --no-keep-empty --empty=drop --force-rebase origin/main
          git push

      - name: Remove obsolete branch
        run: git push origin --delete $GITHUB_REF_NAME
