name: test, format, and push
on:
  push:
    branches: [dev]
    paths: ['**.java']
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout current changes
        run: git rebase $GITHUB_SHA

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test and format the changes
        run: mvn --batch-mode clean verify -Dgpg.skip=true

      - name: Commit and push changes
        run: |
          git -c "user.name=Jenkins" -c "user.email=jenkins@creativecouple.de" commit -a --amend --no-edit --allow-empty
          git rebase --no-keep-empty --empty=drop --force-rebase origin/main
          git push origin HEAD:main
